### API register
POST {{host}}/api/admin/register
Content-Type: application/json

{
  "first_name": "fn",
  "last_name": "ln",
  "email": "email2@email.com",
  "password": "a",
  "password_confirm": "a"
}

### API login
POST {{host}}/api/admin/login
Content-Type: application/json

{
  "email": "email2@email.com",
  "password": "a"
}
